swagger: "2.0"
info:
  title: 'swagger test'
  description: ''
  version: '0.1'
  termsOfService: 'http://swagger.io/terms/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
schemes:
  - "http"
basePath: /api
paths:
  /user/save:
    post:
      tags:
        - "User"
      summary: "save user"
      description: "return init password"
      operationId: saveUser
      produces:
        - "application/json"
      parameters:
        -   in: body
            name: "user"
            required: true
            schema:
              $ref: "#/definitions/User"
      responses:
        200:
          description: "operate success"
          schema:
            type: object
            $ref: "#/definitions/Response"
        400:
          description: "operate down"
          schema:
            type: object
            $ref: "#/definitions/Response"
    get:
      operationId: getUser
      produces:
        - "application/json"
      responses:
        200:
          description: "get user lists"
          schema:
            type: array
            $ref: "#/definitions/Users"


definitions:
  Response:
    type: object
    properties:
      success:
        type: boolean
      code:
        type: string
      message:
        type: string
      data:
        type: object

  User:
    type: object
    required:
      - userNumber
      - userName
    properties:
      id:
        type: integer
        format: int64
      userNumber:
        type: string
        pattern: \d{8}
      userName:
        type: string
        pattern: ^[a-zA-Z]{1,40}$
      phone:
        type: string
        pattern: (\d{10})?
      userStatus:
        type: string
      operatorNumber:
        type: string

  Users:
    type: array
    items:
      $ref: "#/definitions/User"
